x: explicitly include <X11/Xutil.h> instead of relying on <EGL/egl.h>
src/framebuffer.cpp: In member function 'void slop::Framebuffer::setShader(slop::Shader*)':
src/framebuffer.cpp:55:9: error: 'XDestroyImage' was not declared in this scope; did you mean 'eglDestroyImage'?
   55 |         XDestroyImage( image );
      |         ^~~~~~~~~~~~~
      |         eglDestroyImage

src/framebuffer.cpp:55:9: error: use of undeclared identifier 'XDestroyImage'; did you mean 'XDestroyIC'?
        XDestroyImage( image );
        ^~~~~~~~~~~~~
        XDestroyIC
/usr/local/include/X11/Xlib.h:3867:13: note: 'XDestroyIC' declared here
extern void XDestroyIC(
            ^